language: python
python:
  - "2.7"
  - "3.4"
  - "3.9"
env:
  - DJANGO_VERSION=1.8.*
  - DJANGO_VERSION=1.9.*
  - DJANGO_VERSION=1.10.*
  - DJANGO_VERSION=1.11a1
  - DJANGO_VERSION=3.2.12
install:
  - "pip install -r requirements.txt"
  - "pip install Django==$DJANGO_VERSION"
script: "python src/runtests.py"
sudo: false
