# Config file for automatic testing at travis-ci.org

dist: trusty
sudo: required
language: python
python: 3.9
group: deprecated-2017Q3
services:
  - postgresql

addons:
  postgresql: "14"

env:
  - TOX_ENV=py39-django-32
  - TOX_ENV=py39-django-40

matrix:
  fast_finish: true

install: pip install -r requirements-test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV

deploy:
  provider: pypi
  user: $PYPI_USER
  password:
    secure: $PYPI_PASSWORD
  on:
    repo: jjkester/django-auditlog
    branch: stable
    condition: $TOX_ENV = py39-django-32
