# Generated by Django 2.1.7 on 2019-03-21 22:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0009_auto_20190320_1930'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['-timestamp'], name='auditlog_lo_timesta_c1d9bd_idx'),
        ),
    ]
